[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install numpy==1.26.4",
    "pip install torch==2.2.2 --index-url https://download.pytorch.org/whl/cpu",
    "pip install -r requirements.txt --no-deps",
    "pip install -r requirements.txt"
]

[start]
cmd = "python -m uvicorn src.api.app:app --host 0.0.0.0 --port 8080"