services:
  - type: web
    name: enterprise-rag-api
    runtime: python
    buildCommand: "pip install --upgrade pip && pip install torch==2.2.2+cpu --extra-index-url https://download.pytorch.org/whl/cpu && pip install -r requirements.txt"
    startCommand: "python -m uvicorn src.api.app:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: GROQ_API_KEY
        sync: false